Pipeline A15 Farmholdings
statistikZH/statbotData pull request #56
Opened 2023-08-10 14:57 UTC by cmdoret

Add pipeline for dataset A15 (#37)

2023-08-21 15:58 UTC, sabinem requested changes
I like your queries very much: everything looks good now, except, that I added one more column on the metadata_table_columns table: `example_values`. We can discuss this tomorrow with ZHAW. But maybe you could add that column as well. ZHAW mentioned that it would be helpful for them to see example values for the categorical fields and I find that helpful as well.

2023-08-21 15:58 UTC, sabinem commented on pipelines/A15/metadata_table_columns.csv
> +name,table_name,data_type,description
@cmdoret I have added a column `example_values` to the `metadata_table_columns` table, see here: can you please also add this column in your csv file?

2023-08-21 16:12 UTC, cmdoret commented
Thanks, I just added the column. The table is now structured like this
![image](https://github.com/statistikZH/statbotData/assets/22558602/5bc91e93-ad3a-4032-82ac-eaf3d88cfd32)

2023-08-22 08:42 UTC, sabinem approved these changes

2023-08-23 07:42 UTC, merged