shiny app
statistikZH/statbotData pull request #60
Opened 2023-08-15 22:02 UTC by sabinem

2023-08-16 11:05 UTC, av1611 commented
Works and looks good to me.
I think I would add the line breaks for each FROM, JOIN, WHERE

`
stringr::str_replace_all( "FROM", "<br>FROM") %>%
stringr::str_replace_all( "JOIN", "<br>JOIN") %>%
 `

![New Note](https://github.com/statistikZH/statbotData/assets/109128/ec84c50b-51c1-4906-9e40-4194a436b02f)

2023-08-16 13:03 UTC, philbosch requested changes

2023-08-16 13:03 UTC, philbosch commented on R/app.R
> +      stringr::str_remove_all("Query Nr\\. \\d+")
```suggestion
    queries <- queries %>% stringr::str_replace_all( "SELECT", "<span style='font-family:monospace;'>SELECT") %>%
      stringr::str_replace_all(";", ";</span><br><pre>") %>%
      stringr::str_replace_all("--", "</pre><hr><strong>") %>%
      stringr::str_replace_all("\\?", "?</strong><br>") %>%
      stringr::str_remove_all("Query Nr\\. \\d+") %>%
      stringr::str_replace_all("FROM", "<br>FROM") %>%
      stringr::str_replace_all("JOIN", "<br>JOIN") %>%
      stringr::str_replace_all("WHERE", "<br>WHERE") %>%
      stringr::str_replace_all("GROUP BY", "<br>GROUP BY") %>%
      stringr::str_replace_all("ORDER BY", "<br>ORDER BY") %>%
      stringr::str_replace_all("HAVING", "<br>HAVING") %>%
      stringr::str_replace_all("LIMIT", "<br>LIMIT")

```

2023-08-16 13:03 UTC, philbosch commented on R/app.R
> +      stringr::str_remove_all("Query Nr\\. \\d+")
picks up on the suggestion bz @av1611 and includes some more cases

2023-08-17 06:23 UTC, philbosch approved these changes

2023-08-17 06:49 UTC, av1611 approved these changes

2023-08-17 07:46 UTC, merged