Postgres integration
statistikZH/statbotData pull request #83
Opened 2023-09-24 05:08 UTC by sabinem

2023-09-26 12:46 UTC, cmdoret reviewed
I would prefer to minimize the required changes on individual datasets.
With the current implementation of `get_data_types_from_metadata`, we would have to include every column in the metadata files.

Since the purpose of this file thus far was to document columns for humans, this is not the case, and they would need extensive changes.

I will try to rewrite `get_data_types_from_metadata` to infer types froim the dataframe

2023-09-28 14:13 UTC, sabinem commented
Hello Cyril, you wrote: "With the current implementation of `get_data_types_from_metadata`, we would have to include every column in the metadata files." This is not the case: if you look at the function, it adds the missing fields which are `year` or `jahr` and `spatialunit_uid` by itself. The only needed change is to change the data_types from `numeric` and `categorical` to the actual datatypes used in postgres, maybe that wouldn't be so complicated and also be helpful in the long run.

But of course we can also infer data types from the data frame, so yes if you want to do that then go ahead with this approach. It will be also fine with me.

2023-09-29 08:13 UTC, sabinem commented
Hello @cmdoret I went with the proposed approach: only I felt that the numeric fields "NUMERIC" would work better then "DOUBLE PRECISION", see here: https://www.postgresql.org/docs/8.1/datatype.html#DATATYPE-NUMERIC
Therefore I changed all "DOUBLE PRECISION" and replaced them by "NUMERIC", which should even be fine for integers such as `year`.

2023-09-29 08:47 UTC, cmdoret approved these changes

2023-10-02 11:36 UTC, sabinem commented
The PR is now finished: 
- I decided against using scripts for the initial set up, but used package functions instead, that are in `R/postgres_db_initial_setup`
- the `app.R` was moved outside of the package and adapted in a way where it shows the remote data as soon as the pipeline has the status `uploaded`. In that case the queries are also run again against the remote instance, as soon as the pipleline gets loaded in the app
- the repo and pipeline workflow are now described in the `README.md`

2023-10-02 13:27 UTC, cmdoret requested changes
Awesome work! The code is really clear and this is a great improvement overall. Thanks for the readme as well. I added a few suggestions and small fixes.

2023-10-02 13:27 UTC, cmdoret commented on R/testrun_queries.R
> +  print(paste0("Environment:", env, ", Time:", Sys.time()),
```suggestion
  print(paste0("Environment: ", env, ", Time: ", Sys.time()),
```

2023-10-02 13:27 UTC, cmdoret commented on README.md
> +1. Generate Training and Test data for the ML Model from Statistical tables belonging to Swiss Fedearal office of Statistics and selected cantonal statistics offices
```suggestion
1. Generate Training and Test data for the ML Model from Statistical tables belonging to Swiss Federal office of Statistics and selected cantonal statistics offices
```

2023-10-02 13:27 UTC, cmdoret commented on README.md
> +- **pipelines**: in `pipelines`: they contain the dataset processing as it is preapared for the postgres import and the test data for the ML per dataset
```suggestion
- **pipelines**: in `pipelines`: they contain the dataset processing as it is preapared for the postgres import and the test data (question / SQL query pairs) for the ML model per dataset
```

2023-10-02 13:27 UTC, cmdoret commented on README.md
> +The pipelines are intended to process datasets and the upload them to a remote postgres instance.
```suggestion
The pipelines are intended to process datasets and the upload them to a remote postgres instance, for which the credentials can be configured using the `.env` file (`sample.env` is provided as template).
```

2023-10-02 13:27 UTC, cmdoret commented on README.md
> +The queries in queries.sql` can either run on the this tibble or on the remote postgres instance. Where they run depends on the pipeline status `ds$status`
```suggestion
The queries in `queries.sql` can either run on the this tibble or on the remote postgres instance. Where they run depends on the pipeline status `ds$status`
```
md formatting

2023-10-02 14:01 UTC, cmdoret approved these changes
Looks good to me!

2023-10-02 14:05 UTC, merged